<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // ─── Fiksi ────────────────────────────────────────────────────────────────
            [
                'category'    => 'Fiksi',
                'title'       => 'Laskar Pelangi',
                'author'      => 'Andrea Hirata',
                'publisher'   => 'Bentang Pustaka',
                'year'        => 2005,
                'description' => 'Kisah perjuangan 10 anak kampung Belitung dalam mengejar mimpi mereka di tengah keterbatasan fasilitas sekolah.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/7079796-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Bumi Manusia',
                'author'      => 'Pramoedya Ananta Toer',
                'publisher'   => 'Lentera Dipantara',
                'year'        => 1980,
                'description' => 'Roman sejarah tentang perjuangan dan cinta di era kolonial Belanda, bab pertama dari Tetralogi Pulau Buru.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/6643692-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Dilan: Dia adalah Dilanku Tahun 1990',
                'author'      => 'Pidi Baiq',
                'publisher'   => 'Mizan Pustaka',
                'year'        => 2014,
                'description' => 'Kisah cinta remaja di Bandung tahun 1990 antara Milea dan Dilan, pria penuh pesona.',
                'cover_url'   => 'https://upload.wikimedia.org/wikipedia/id/c/c5/Dilan_1990.jpg',
                'stock'       => 4,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Perahu Kertas',
                'author'      => 'Dee Lestari',
                'publisher'   => 'Bentang Pustaka',
                'year'        => 2009,
                'description' => 'Kisah dua jiwa, Kugy dan Keenan, yang mencari jati diri, impian, dan cinta sejati mereka.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8705088-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Ayat-Ayat Cinta',
                'author'      => 'Habiburrahman El Shirazy',
                'publisher'   => 'Republika',
                'year'        => 2004,
                'description' => 'Novel romantis islami tentang perjalanan cinta Fahri, mahasiswa Indonesia di Mesir.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/9904402-L.jpg',
                'stock'       => 4,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Negeri 5 Menara',
                'author'      => 'A. Fuadi',
                'publisher'   => 'Gramedia',
                'year'        => 2009,
                'description' => 'Kisah persahabatan dan perjuangan enam santri di Pondok Madani yang mengejar impian ke lima menara dunia.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/14303993-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Ronggeng Dukuh Paruk',
                'author'      => 'Ahmad Tohari',
                'publisher'   => 'Gramedia Pustaka Utama',
                'year'        => 1982,
                'description' => 'Kisah penari ronggeng di sebuah dukuh kecil yang terisolasi di Jawa, berlatar belakang gejolak sosial politik tahun 1960-an.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8302061-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Supernova: Kesatria, Putri, dan Bintang Jatuh',
                'author'      => 'Dee Lestari',
                'publisher'   => 'Truedee Books',
                'year'        => 2001,
                'description' => 'Novel fiksi sains filosofis tentang cinta, sains, dan spiritualitas yang saling berkelindan di era modern.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12836263-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Gadis Kretek',
                'author'      => 'Ratih Kumala',
                'publisher'   => 'Gramedia Pustaka Utama',
                'year'        => 2012,
                'description' => 'Penelusuran sejarah pabrik kretek lokal dan kisah cinta tragis di Jawa Tengah dari masa penjajahan hingga era modern.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/14414619-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Fiksi',
                'title'       => 'Cantik Itu Luka',
                'author'      => 'Eka Kurniawan',
                'publisher'   => 'Gramedia Pustaka Utama',
                'year'        => 2002,
                'description' => 'Karya realisme magis epik yang menggambarkan sejarah berdarah Indonesia melalui kehidupan seorang pelacur dan keturunannya.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8296767-L.jpg',
                'stock'       => 2,
            ],

            // ─── Non-Fiksi ────────────────────────────────────────────────────────────
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Atomic Habits',
                'author'      => 'James Clear',
                'publisher'   => 'Gramedia Pustaka Utama',
                'year'        => 2019,
                'description' => 'Panduan berbasis riset tentang cara membangun kebiasaan baik dan menghancurkan kebiasaan buruk secara sistematis.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12539702-L.jpg',
                'stock'       => 5,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Sapiens: A Brief History of Humankind',
                'author'      => 'Yuval Noah Harari',
                'publisher'   => 'KPG',
                'year'        => 2011,
                'description' => 'Sejarah singkat umat manusia dari zaman batu hingga era modern yang mengubah pandangan kita tentang dunia.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8634250-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Rich Dad Poor Dad',
                'author'      => 'Robert T. Kiyosaki',
                'publisher'   => 'Gramedia',
                'year'        => 1997,
                'description' => 'Pelajaran finansial dari dua ayah dengan pandangan berbeda tentang uang, aset, dan kebebasan finansial.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8315603-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Thinking, Fast and Slow',
                'author'      => 'Daniel Kahneman',
                'publisher'   => 'Farrar, Straus and Giroux',
                'year'        => 2011,
                'description' => 'Mengenali dua sistem pemikiran dalam diri kita: sistem cepat intuitif dan sistem lambat analitis.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/13290711-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Homo Deus: A Brief History of Tomorrow',
                'author'      => 'Yuval Noah Harari',
                'publisher'   => 'Harvill Secker',
                'year'        => 2015,
                'description' => 'Menjelajahi masa depan umat manusia saat kecerdasan buatan dan bioteknologi mulai mengambil alih peradaban.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8447814-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'Start With Why',
                'author'      => 'Simon Sinek',
                'publisher'   => 'Portfolio',
                'year'        => 2009,
                'description' => 'Bagaimana para pemimpin hebat menginspirasi orang lain untuk bertindak dengan memulai dari pertanyaan mengapa.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10255474-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Non-Fiksi',
                'title'       => 'The 7 Habits of Highly Effective People',
                'author'      => 'Stephen R. Covey',
                'publisher'   => 'Free Press',
                'year'        => 1989,
                'description' => 'Tujuh kebiasaan utama untuk mencapai efektivitas pribadi dan profesional secara holistik.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/9266857-L.jpg',
                'stock'       => 3,
            ],

            // ─── Teknologi ────────────────────────────────────────────────────────────
            [
                'category'    => 'Teknologi',
                'title'       => 'Clean Code',
                'author'      => 'Robert C. Martin',
                'publisher'   => 'Prentice Hall',
                'year'        => 2008,
                'description' => 'Panduan praktis menulis kode yang bersih, mudah dibaca, dan maintainable untuk programmer profesional.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8065615-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Teknologi',
                'title'       => 'The Pragmatic Programmer',
                'author'      => 'Andrew Hunt',
                'publisher'   => 'Addison-Wesley',
                'year'        => 1999,
                'description' => 'Panduan klasik untuk menjadi programmer yang lebih pragmatis, produktif, dan profesional.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10143650-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Teknologi',
                'title'       => 'Design Patterns',
                'author'      => 'Erich Gamma',
                'publisher'   => 'Addison-Wesley',
                'year'        => 1994,
                'description' => 'Buku gang of four tentang 23 pola desain reusable untuk arsitektur perangkat lunak berorientasi objek.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/6601119-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Teknologi',
                'title'       => 'Refactoring: Improving the Design of Existing Code',
                'author'      => 'Martin Fowler',
                'publisher'   => 'Addison-Wesley',
                'year'        => 1999,
                'description' => 'Seni merestrukturisasi kode program yang sudah ada untuk meningkatkan kualitas desain tanpa mengubah perilakunya.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10486828-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Teknologi',
                'title'       => 'Introduction to Algorithms',
                'author'      => 'Thomas H. Cormen',
                'publisher'   => 'MIT Press',
                'year'        => 2009,
                'description' => 'Buku pegangan komprehensif tentang algoritma komputer, mulai dari struktur data dasar hingga algoritma kompleks.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8384464-L.jpg',
                'stock'       => 2,
            ],

            // ─── Sejarah ──────────────────────────────────────────────────────────────
            [
                'category'    => 'Sejarah',
                'title'       => 'Sejarah Indonesia Modern 1200-2004',
                'author'      => 'M.C. Ricklefs',
                'publisher'   => 'Serambi',
                'year'        => 2008,
                'description' => 'Tinjauan komprehensif sejarah Indonesia dari kerajaan-kerajaan Hindu-Buddha hingga era Reformasi.',
                'cover_url'   => 'https://upload.wikimedia.org/wikipedia/id/d/dc/Sejarah_Indonesia_Modern.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sejarah',
                'title'       => 'Arus Balik',
                'author'      => 'Pramoedya Ananta Toer',
                'publisher'   => 'Hasta Mitra',
                'year'        => 1995,
                'description' => 'Novel sejarah epik tentang awal abad Nusantara dan kedatangan bangsa asing yang mengubah segalanya.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/3842927-L.jpg',
                'stock'       => 1,
            ],
            [
                'category'    => 'Sejarah',
                'title'       => 'Guns, Germs, and Steel',
                'author'      => 'Jared Diamond',
                'publisher'   => 'W. W. Norton & Company',
                'year'        => 1997,
                'description' => 'Analisis mendalam mengenai faktor lingkungan dan geografis yang membentuk nasib peradaban manusia.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8254881-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sejarah',
                'title'       => 'A History of Modern Indonesia since c. 1200',
                'author'      => 'M. C. Ricklefs',
                'publisher'   => 'Palgrave Macmillan',
                'year'        => 2001,
                'description' => 'Analisis mendetail tentang perubahan sosial, agama, ekonomi, dan politik di Nusantara.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/9525287-L.jpg',
                'stock'       => 2,
            ],

            // ─── Biografi ─────────────────────────────────────────────────────────────
            [
                'category'    => 'Biografi',
                'title'       => 'Elon Musk',
                'author'      => 'Walter Isaacson',
                'publisher'   => 'Simon & Schuster',
                'year'        => 2023,
                'description' => 'Biografi lengkap dan mendalam tentang pendiri Tesla, SpaceX, dan X oleh penulis terkemuka Walter Isaacson.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/14420016-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Biografi',
                'title'       => 'Steve Jobs',
                'author'      => 'Walter Isaacson',
                'publisher'   => 'Simon & Schuster',
                'year'        => 2011,
                'description' => 'Biografi eksklusif pendiri Apple yang ditulis berdasarkan lebih dari 40 wawancara langsung dengan Steve Jobs.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12374726-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Biografi',
                'title'       => 'Soekarno: An Autobiography',
                'author'      => 'Cindy Adams',
                'publisher'   => 'Gunung Agung',
                'year'        => 1965,
                'description' => 'Autobiografi Presiden pertama Indonesia yang diceritakan langsung kepada jurnalis Amerika, Cindy Adams.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/9516402-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Biografi',
                'title'       => 'Long Walk to Freedom',
                'author'      => 'Nelson Mandela',
                'publisher'   => 'Little, Brown & Co',
                'year'        => 1994,
                'description' => 'Kisah hidup Nelson Mandela, dari masa kecilnya hingga perjuangannya melawan apartheid di Afrika Selatan.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10543666-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Biografi',
                'title'       => 'Gerpolek: Gerilya-Politik-Ekonomi',
                'author'      => 'Tan Malaka',
                'publisher'   => 'Sopo Tresno',
                'year'        => 1948,
                'description' => 'Manifesto politik dan strategi perjuangan gerilya Tan Malaka saat dipenjara di Madiun.',
                'cover_url'   => 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Gerpolek_front.jpg',
                'stock'       => 2,
            ],

            // ─── Sains ────────────────────────────────────────────────────────────────
            [
                'category'    => 'Sains',
                'title'       => 'A Brief History of Time',
                'author'      => 'Stephen Hawking',
                'publisher'   => 'Bantam Books',
                'year'        => 1988,
                'description' => 'Penjelasan ilmu fisika dan kosmologi — dari Big Bang hingga lubang hitam — untuk pembaca awam.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10432365-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sains',
                'title'       => 'Cosmos',
                'author'      => 'Carl Sagan',
                'publisher'   => 'Random House',
                'year'        => 1980,
                'description' => 'Perjalanan personal melalui ruang dan waktu, menjelajahi asal usul alam sem universe dan tempat manusia di dalamnya.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8283901-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sains',
                'title'       => 'A Short History of Nearly Everything',
                'author'      => 'Bill Bryson',
                'publisher'   => 'KPG',
                'year'        => 2003,
                'description' => 'Perjalanan menyenangkan menjelajahi ilmu pengetahuan alam — dari fisika partikel hingga geologi bumi.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12725620-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Sains',
                'title'       => 'The Selfish Gene',
                'author'      => 'Richard Dawkins',
                'publisher'   => 'Oxford University Press',
                'year'        => 1976,
                'description' => 'Karya revolusioner tentang biologi evolusi yang menempatkan gen sebagai pusat agen seleksi alam.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12865913-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sains',
                'title'       => 'The Elegant Universe',
                'author'      => 'Brian Greene',
                'publisher'   => 'W. W. Norton & Company',
                'year'        => 1999,
                'description' => 'Menjelajahi teori dawai (string theory) dan upaya para ilmuwan menyatukan fisika kuantum dengan relativitas umum.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8232986-L.jpg',
                'stock'       => 2,
            ],

            // ─── Pendidikan ───────────────────────────────────────────────────────────
            [
                'category'    => 'Pendidikan',
                'title'       => 'Matematika SMA Kelas XII',
                'author'      => 'Drs. Sartono Wirodikromo',
                'publisher'   => 'Erlangga',
                'year'        => 2020,
                'description' => 'Buku pelajaran matematika lengkap untuk kelas XII SMA dengan soal-soal latihan dan pembahasan mendalam.',
                'cover_url'   => 'https://static.buku.kemdikbud.go.id/content/image/cover/cov_kelas_12_matematika_bg.png',
                'stock'       => 5,
            ],
            [
                'category'    => 'Pendidikan',
                'title'       => 'Fisika untuk SMA Kelas XI',
                'author'      => 'Marthen Kanginan',
                'publisher'   => 'Erlangga',
                'year'        => 2021,
                'description' => 'Buku fisika SMA terpercaya dengan penjelasan konsep yang komprehensif dan latihan soal terstruktur.',
                'cover_url'   => 'https://static.buku.kemdikbud.go.id/content/image/cover/cov_kelas_11_fisika_bg.png',
                'stock'       => 4,
            ],
            [
                'category'    => 'Pendidikan',
                'title'       => 'Bahasa Indonesia untuk SMA Kelas XII',
                'author'      => 'Tim Pengajar',
                'publisher'   => 'Erlangga',
                'year'        => 2022,
                'description' => 'Buku pelajaran bahasa Indonesia lengkap untuk SMA yang mencakup tata bahasa, sastra, dan keterampilan menulis.',
                'cover_url'   => 'https://static.buku.kemdikbud.go.id/content/image/cover/cov_kelas_12_bahasa_indonesia_bg.png',
                'stock'       => 5,
            ],
            [
                'category'    => 'Pendidikan',
                'title'       => 'Kimia untuk SMA Kelas XI',
                'author'      => 'Unggul Sudarmo',
                'publisher'   => 'Erlangga',
                'year'        => 2021,
                'description' => 'Buku pelajaran kimia kelas XI dengan materi lengkap mengenai larutan asam-basa, termokimia, dan hidrokarbon.',
                'cover_url'   => 'https://static.buku.kemdikbud.go.id/content/image/cover/cov_kelas_11_kimia_bg.png',
                'stock'       => 4,
            ],
            [
                'category'    => 'Pendidikan',
                'title'       => 'Biologi untuk SMA Kelas XI',
                'author'      => 'Diah Aryulina',
                'publisher'   => 'Erlangga',
                'year'        => 2021,
                'description' => 'Buku pelajaran biologi yang mengkaji secara mendalam struktur sel, jaringan, dan sistem organ manusia serta tumbuhan.',
                'cover_url'   => 'https://static.buku.kemdikbud.go.id/content/image/cover/cov_kelas_11_biologi_bg.png',
                'stock'       => 4,
            ],

            // ─── Agama ────────────────────────────────────────────────────────────────
            [
                'category'    => 'Agama',
                'title'       => 'Fiqih Islam',
                'author'      => 'H. Sulaiman Rasjid',
                'publisher'   => 'Sinar Baru Algensindo',
                'year'        => 2010,
                'description' => 'Panduan fiqih Islam yang lengkap dan mudah dipahami, mencakup ibadah, muamalah, dan akhlak.',
                'cover_url'   => 'https://www.sinarbaru.co.id/images/products/FIQIH-ISLAM.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Agama',
                'title'       => 'Tafsir Al-Misbah',
                'author'      => 'M. Quraish Shihab',
                'publisher'   => 'Lentera Hati',
                'year'        => 2015,
                'description' => 'Tafsir Al-Quran kontemporer yang komprehensif dengan pendekatan bahasa, konteks budaya, dan relevansi modern.',
                'cover_url'   => 'https://lenterahati.com/wp-content/uploads/2019/04/Tafsir-Al-Misbah-Lengkap-Volume-1-15-M-Quraish-Shihab.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Agama',
                'title'       => 'Ringkasan Ihya Ulumuddin',
                'author'      => 'Imam Al-Ghazali',
                'publisher'   => 'Tiga Serangkai',
                'year'        => 2012,
                'description' => 'Ringkasan dari kitab monumental Ihya Ulumuddin yang mengkaji tasawuf, pensucian jiwa (tazkiyatun nafs), dan akhlak.',
                'cover_url'   => 'https://api.wawasanislam.com/asset/images/kitab-ihya-ulumuddin.jpg',
                'stock'       => 3,
            ],

            // ─── Sastra ───────────────────────────────────────────────────────────────
            [
                'category'    => 'Sastra',
                'title'       => 'Sitti Nurbaya',
                'author'      => 'Marah Rusli',
                'publisher'   => 'Balai Pustaka',
                'year'        => 1922,
                'description' => 'Novel klasik Melayu tentang kisah cinta tragis Sitti Nurbaya dan Samsulbahri yang dipisahkan adat dan kekuasaan.',
                'cover_url'   => 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Sitti_Nurbaya_novel_cover.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sastra',
                'title'       => 'Salah Asuhan',
                'author'      => 'Abdoel Moeis',
                'publisher'   => 'Balai Pustaka',
                'year'        => 1928,
                'description' => 'Novel klasik Indonesia tentang konflik budaya Barat dan Timur yang dialami seorang pemuda terdidik.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/7104772-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Sastra',
                'title'       => 'Layar Terkembang',
                'author'      => 'Sutan Takdir Alisjahbana',
                'publisher'   => 'Balai Pustaka',
                'year'        => 1936,
                'description' => 'Novel emansipasi wanita pertama di Indonesia yang mengisahkan pemikiran modern wanita Nusantara di era pergerakan.',
                'cover_url'   => 'https://upload.wikimedia.org/wikipedia/id/5/52/Layar_Terkembang.jpg',
                'stock'       => 2,
            ],

            // ─── Kesehatan ────────────────────────────────────────────────────────────
            [
                'category'    => 'Kesehatan',
                'title'       => 'The Body: A Guide for Occupants',
                'author'      => 'Bill Bryson',
                'publisher'   => 'Doubleday',
                'year'        => 2019,
                'description' => 'Panduan menakjubkan dan menghibur tentang cara kerja tubuh manusia, ditulis untuk semua kalangan.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/12722746-L.jpg',
                'stock'       => 2,
            ],
            [
                'category'    => 'Kesehatan',
                'title'       => 'Why We Sleep',
                'author'      => 'Matthew Walker',
                'publisher'   => 'Scribner',
                'year'        => 2017,
                'description' => 'Penelitian ilmiah terbaru tentang pentingnya tidur dan dampaknya terhadap kesehatan fisik dan mental.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/8814155-L.jpg',
                'stock'       => 3,
            ],
            [
                'category'    => 'Kesehatan',
                'title'       => 'Breath: The New Science of a Lost Art',
                'author'      => 'James Nestor',
                'publisher'   => 'Riverhead Books',
                'year'        => 2020,
                'description' => 'Menjelajahi cara bernapas yang benar dan pengaruh luar biasanya bagi kesehatan paru-paru, mental, dan fisik.',
                'cover_url'   => 'https://covers.openlibrary.org/b/id/10523274-L.jpg',
                'stock'       => 2,
            ],
        ];

        foreach ($books as $b) {
            $category = Category::where('name', $b['category'])->first();
            if (!$category) continue;

            Book::updateOrCreate(
                ['title' => $b['title'], 'author' => $b['author']],
                [
                    'category_id'  => $category->id,
                    'title'        => $b['title'],
                    'author'       => $b['author'],
                    'publisher'    => $b['publisher'],
                    'year'         => $b['year'],
                    'description'  => $b['description'],
                    'cover_url'    => $b['cover_url'],
                    'stock'        => $b['stock'],
                    'availability' => 'available',
                ]
            );
        }
    }
}
